# Native R Travis Github

language: r
r:
  - release
#  - devel
# sudo: required

cache:
  packages: true

# Be strict when checking our package
warnings_are_errors: true
r_packages:
  - devtools

#r_github_packages:
#  - jimhester/covr

before_install:
  - cd rpackage

#after_success:
#  - Rscript -e 'covr::coveralls()'

notifications:
  email:
    on_success: change
    on_failure: change
